apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: jaeger-tracing
spec:
  strategy: production
  storage:
    type: elasticsearch
    secretName: jaeger-es-credentials
    options:
      es:
        server-urls: https://172.18.0.2:9200
        version: 7
        create-index-templates: "false"
        tls:
          skip-host-verify: "true"
