apiVersion: v1
kind: Service
metadata:
  name: jaeger-tracing-query-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: jaeger-tracing
  ports:
    - protocol: TCP
      port: 16686
      targetPort: 16686
      nodePort: 32503

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-tracing-agent-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: jaeger-tracing
  ports:
    - protocol: UDP
      port: 5775
      targetPort: 5775
      name: port-1
    - protocol: TCP
      port: 5778
      targetPort: 5778
      name: port-2
    - protocol: UDP
      port: 6831
      targetPort: 6831
      name: port-3
    - protocol: UDP
      port: 6832
      targetPort: 6832
      name: port-4

---
apiVersion: v1
kind: Service
metadata:
  name: jaeger-tracing-collector-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: jaeger-tracing
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
      name: port-1
    - protocol: TCP
      port: 14250
      targetPort: 14250
      name: port-2
    - protocol: UDP
      port: 14267
      targetPort: 14267
      name: port-3
    - protocol: UDP
      port: 14268
      targetPort: 14268
      name: port-4
    - protocol: UDP
      port: 4317
      targetPort: 4317
      name: port-5
    - protocol: UDP
      port: 4318
      targetPort: 4318
      name: port-6
